language: node_js
node_js:
  - stable 
services: mongodb  
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install
script:
  - npm test
  - codecov
deploy:
  app: duka
  provider: heroku
  api_key: ${HEROKU_API_KEY}
