language: node_js
node_js:
  - "stable" 
services: mongodb  
cache:  
  directories:
    - "node_modules"
  yarn: true
install:
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm install
script:
  - npm test
  - codecov
  - codacy-coverage
deploy:
  app: duka-api
  provider: heroku
  api_key: ${HEROKU_API_KEY}
